language: java
jdk:
  - oraclejdk8

# Skip the "installation" step:
# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true

script:
  # Builds the compiler and runs tests
  - mvn install --batch-mode

